#!/usr/bin/env sh
#
#
#
ENCLAVE_FS=$1
ENCLAVE_SIZE="$(ls -lh $1 | awk '{print $5}' | tail -n1)" #double pipe classic
ENCLAVE_LOOP="$(sudo losetup -f)"

echo ~****~**~~*~*~*~*~**~**~*~*~****~*~*~*~*~***~*~*~***~*~*~***~**~*~*~****~*~*~*~*~***~*~*~*~**~*~*~**

generate_rand_file () {
	read -p "            desired size? 
                    enter e.g. '1' for 1*(2^10)^2 Bytes (=1MiB) or '4K' (=4000) for 4GiB
                    enter now: " input

			if [ ! -w $PWD ];
		  		then twd=$HOME ;
				else twd=$PWD
			fi
		  	outfile=$twd/encl.rand
			echo "writing random (indeciferable) values to $twd/encl.rand"
	dd if=/dev/urandom of=$outfile bs=1024 count="$input"x1024 status=progress
}
generate_rand_file

activate_rnd_fs () {
	sudo bash -c "
	     losetup --direct-io=on $ENCLAVE_LOOP $ENCLAVE_FS
	     cryptsetup open $ENCLAVE_LOOP --type=luks2 rnd
	     lvscan
	     "
}

setup_logical_volume () {
	if [ -z "$(sudo pvs)" ];
		 then sudo pvcreate /dev/mapper/rnd ;
	fi
	if [ -z "$(sudo vgs)" ];
		then sudo vgcreate rnd /dev/mapper/rnd ;
	fi
	if [ -z "$(sudo lvs)" ];
    		then sudo lvcreate -n benclave -l 100%FREE rnd ;
	fi
}

deactivate_benclave () {
   sudo bash -c "lvchange -an rnd
   		 cryptsetup close rnd
   		 losetup -D"
} 

